Aula 16 do curso git gihub
Mensagem dentro do bash do git


$ git push origin main
Enter passphrase for key '/c/Users/Oliveira/.ssh/id_ed25519':
To github.com:SergioRibeiro7820/github-course.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'github.com:SergioRibeiro7820/github-course.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.